### ISSUE TITLE
Process killed at FASTA format check, no error msg

### ISSUE THREAD

**Issue by DrPintoThe2nd** [hoelzer/poseidon#25]
Dear Poseidon team,

I am at a loss, I have subset the data and changed names, etc. The pipeline quits without an error..

[Running 48 thread Ubuntu 16.04 w/ 128Gb RAM.. should be no issues there.]

The only thing I can think of is the translation scheme is non-standard.. comments, suggestions, help?

""
bjp$ nextflow run hoelzer/poseidon -r v1.0.1 --fasta ~/poseidon/test_data/seq.fasta -profile local,docker
N E X T F L O W  ~  version 20.10.0
Launching `hoelzer/poseidon` [intergalactic_mirzakhani] - revision: 4f23bb667f [v1.0.1]
WARN: DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
 
P O S E I D O N
 
Profile: local,docker
 
Current User: bjp
Nextflow-version: 20.10.0
Starting time: 01-11-2020 15:14 UTC
Workdir location: /tmp/nextflow-work-bjp
 
CPUs to use per process: 6, maximal CPUs to use: 48
 
Tree root species: NA
Reference species: NA
 
Use KH-insignificant breakpoints: no
 
[-        ] process > check_fasta_format   -
[-        ] process > translatorx          -
[-        ] process > check_aln            -
[-        ] process > remove_gaps          -
[-        ] process > raxml_nt             -
[-        ] process > raxml_aa             -
executor >  local (1)
[4a/8e9e14] process > check_fasta_format (1) [  0%] 0 of 1
[-        ] process > translatorx            -
[-        ] process > check_aln              -
[-        ] process > remove_gaps            -
[-        ] process > raxml_nt               -
[-        ] process > raxml_aa               -
executor >  local (1)
[4a/8e9e14] process > check_fasta_format (1) [  0%] 0 of 1
[-        ] process > translatorx            -
[-        ] process > check_aln              -
[-        ] process > remove_gaps            -
[-        ] process > raxml_nt               -
[-        ] process > raxml_aa               -
[-        ] process > raxml2drawing          -
bjp:~/poseidon$    -                                                             [<------------and it does this?]
[-        ] process > barefoot               -
[-        ] process > model_selection        -
[-        ] process > gard_detect            -
[-        ] process > gard_process           -
[-        ] process > codeml_built           -
[-        ] process > codeml_run             -
[-        ] process > codeml_combine         -
[-        ] process > tex_built              -
[-        ] process > pdflatex_single        -
[-        ] process > build_fragments        -
[-        ] process > frag_raxml_nt          -
[-        ] process > frag_raxml_aa          -
[-        ] process > frag_raxml2drawing     -
[-        ] process > frag_nw_display        -
[-        ] process > frag_barefoot          -
[-        ] process > frag_codeml_built      -
[-        ] process > frag_codeml_run        -
[-        ] process > frag_codeml_combine    -
[-        ] process > frag_tex_built         -
[-        ] process > frag_pdflatex_single   -
[-        ] process > tex_combine            -
[-        ] process > pdflatex_full          -
[-        ] process > frag_aln_html          -
[-        ] process > html_frag              -
[-        ] process > frag_publish           -
[-        ] process > frag_html_codeml       -
[-        ] process > html                   -
[-        ] process > html_codeml            -
[-        ] process > html_params            -
[-        ] process > html_recomb            -
""
Thanks so much!
Best,
bjp

**Comment by hoelzer** [comment]
Hi @DrPintoThe2nd ! 

Thanks for your interest in using PoSeiDon! 

Can you check the files in the folder 

```
ls -lah /tmp/nextflow-work-bjp/4a/8e9e14]*/
```

?

There should be a `.command.log` that might give us some more insight into what's going on. 

Does your FASTA file contain protein-coding homologous sequences?

**Comment by DrPintoThe2nd** [comment]
Hi Martin,

Thanks for your timely response. I've been pulled away on some other projects and my collaborator has decided to try and work through the issue. I'll close for now and re-open if I have some time to continue troubleshooting.

Thanks again,
bjp
