### ISSUE TITLE
Error running test files

### ISSUE THREAD

**Issue by koushik1989** [hoelzer/poseidon#29]
Dear Developers, thank you for developing a wonderful tool like PoseiDon. I installed nextflow version 20.04.1.5335 and docker 20.10.10 and followed every step mentioned in github. 
But when I run the following test run I get an error. 

$ nextflow run hoelzer/poseidon -r v1.0.1 -profile local,docker --fasta ~/.nextflow/assets/hoelzer/poseidon/test_data/bats_mx1_small.fasta
N E X T F L O W  ~  version 20.12.0-edge
Launching `hoelzer/poseidon` [goofy_liskov] - revision: 4f23bb667f [v1.0.1]
WARN: DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
 
P O S E I D O N
 
Profile: local,docker
 
Current User: fly-lab
Nextflow-version: 20.12.0-edge
Starting time: 12-12-2020 09:14 UTC
Workdir location: /tmp/nextflow-work-fly-lab
 
CPUs to use per process: 6, maximal CPUs to use: 4
 
Tree root species: NA
Reference species: NA
 
Use KH-insignificant breakpoints: no
 
executor >  local (1)
[dd/1d80b5] process > check_fasta_format (1) [  0%] 0 of 1
[-        ] process > translatorx            -
[-        ] process > check_aln              -
[-        ] process > remove_gaps            -
[-        ] process > raxml_nt               -
[-        ] process > raxml_aa               -
[-        ] process > raxml2drawing          -
[-        ] process > nw_display             -
[-        ] process > barefoot               -
[-        ] process > model_selection        -
[-        ] process > gard_detect            -
[-        ] process > gard_process           -
[-        ] process > codeml_built           -
[-        ] process > codeml_run             -
[-        ] process > codeml_combine         -
[-        ] process > tex_built              -
[-        ] process > pdflatex_single        -
[-        ] process > build_fragments        -
[-        ] process > frag_raxml_nt          -
[-        ] process > frag_raxml_aa          -
[-        ] process > frag_raxml2drawing     -
[-        ] process > frag_nw_display        -
[-        ] process > frag_barefoot          -
[-        ] process > frag_codeml_built      -
executor >  local (1)
[dd/1d80b5] process > check_fasta_format (1) [100%] 1 of 1, failed: 1 ✘
[-        ] process > translatorx            -
[-        ] process > check_aln              -
[-        ] process > remove_gaps            -
[-        ] process > raxml_nt               -
[-        ] process > raxml_aa               -
[-        ] process > raxml2drawing          -
[-        ] process > nw_display             -
[-        ] process > barefoot               -
[-        ] process > model_selection        -
[-        ] process > gard_detect            -
[-        ] process > gard_process           -
[-        ] process > codeml_built           -
[-        ] process > codeml_run             -
[-        ] process > codeml_combine         -
[-        ] process > tex_built              -
[-        ] process > pdflatex_single        -
[-        ] process > build_fragments        -
[-        ] process > frag_raxml_nt          -
[-        ] process > frag_raxml_aa          -
[-        ] process > frag_raxml2drawing     -
[-        ] process > frag_nw_display        -
[-        ] process > frag_barefoot          -
[-        ] process > frag_codeml_built      -
[-        ] process > frag_codeml_run        -
[-        ] process > frag_codeml_combine    -
[-        ] process > frag_tex_built         -
[-        ] process > frag_pdflatex_single   -
[-        ] process > tex_combine            -
[-        ] process > pdflatex_full          -
[-        ] process > frag_aln_html          -
[-        ] process > html_frag              -
[-        ] process > frag_publish           -
[-        ] process > frag_html_codeml       -
[-        ] process > html                   -
[-        ] process > html_codeml            -
[-        ] process > html_params            -
[-        ] process > html_recomb            -
Error executing process > 'check_fasta_format (1)'

Caused by:
  Process `check_fasta_format (1)` terminated with an error exit status (126)

Command executed:

  fasta_format_checker.rb bats_mx1_small.fasta bats_mx1_small.checked.fasta bats_mx1_small.log bats_mx1_small_internal2input_species.tsv bats_mx1_small_input2internal_species.tsv NA NA
  
  # replace newlines with 'foobar' to replace this again in the nextflow for better terminal output
  LOG=$(sed -z 's/\n/foobar/g' bats_mx1_small.log)

Command exit status:
  126

Command output:
  (empty)

Command error:
  docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=nxf-Aq2yz0pzT8039End0fK0PHYw": dial unix /var/run/docker.sock: connect: permission denied.
  See 'docker run --help'.

Work dir:
  /tmp/nextflow-work-fly-lab/dd/1d80b54011f8c12626687a7eb28915

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

Kindly help me out as PoseiDon is the only hope for a biologist like me with no much coding knowledge.

**Comment by koushik1989** [comment]
Dear developers, I have successfully resolved the issue. The problem was with Docker.

Thanks.

**Comment by hoelzer** [comment]
Great, thanks for your interest into the tool!
